' --------------------------------------------------
' 新規作成日：2021-02-19
' 最終更新日：2021-02-19
' 機能：Robustness Diagramの基本要素
' --------------------------------------------------

@startuml

title Robustness Diagram

left to right direction

usecase actor1がprocess1する

' --------------------------------------------------
' data definition
' --------------------------------------------------
actor actor1 as a1
boundary screen1 as b1
control process1 as c1
entity text_file1 as e1
database database1 as d1

' --------------------------------------------------
' data processing
' --------------------------------------------------
a1 -> b1: screen1.input1(message1)
b1 -> c1: process1.input1(message2)
c1 .> e1: process1.input2(message3)
c1 .> d1: process1.input3(message4)

@enduml
