' --------------------------------------------------
' Function    : Class_Diagram5
' Author      : T. TANAKA
' Description : Class Diagramの基本要素
'                   カーディナリティ（濃度）
'                   別名：例"Person"をc1という別名にする
' --------------------------------------------------

@startuml

title Class Diagram

' left to right direction

' --------------------------------------------------
' Category Definition
' --------------------------------------------------
package p1{
    interface i1{
        + hoge()
        + fuga()
    }

    class "Person" as c1{
        - string name [1]
        - int age [0..1]
        + set(name, age)
        + get()
    }
    class "Car" as c2
}

enum e1{
    value1
    value2
    value3
}

package p2{
    class c3
}

' --------------------------------------------------
' Category Connection
' --------------------------------------------------
i1 <|-- c1
c1 *--> c2

c2 "0..*"..> "1" c3

@enduml
