' --------------------------------------------------
' Function    : Sequence_Diagram2
' Author      : T. TANAKA
' Description : Sequence Diagram の基本要素
' --------------------------------------------------

@startuml

title Sequence Diagram ( y = f(x) )

' --------------------------------------------------
' data definition
' --------------------------------------------------
actor actor1 as a1
actor object1 as o1

' --------------------------------------------------
' y = f(x)
' --------------------------------------------------
group sub-routine1
  a1 -> o1 : request f(x)
  a1 <-- o1 : response y
'  o1 --> a1
end

' --------------------------------------------------

@enduml
