' --------------------------------------------------
' Function    : Sequence_Diagram
' Author      : T. TANAKA
' Description : Sequence Diagram の基本要素
' --------------------------------------------------

@startuml

title Sequence Diagram

' --------------------------------------------------
' data definition
' --------------------------------------------------
actor actor1 as a1
actor object1 as o1
actor object2 as o2
actor object3 as o3

' --------------------------------------------------
' Alternative (if文)
' --------------------------------------------------
group sub-routine1
  alt case1
    a1 -> o1 : actiivity1
    a1 <-- o1
'    o1 --> a1
  else case2
    a1 -> o2: actiivity2
    a1 <-- o2
'    o2 --> a1
  else others
    a1 -> o3: actiivity3
    a1 <-- o3
'    o3 --> a1
  end
end

' --------------------------------------------------
' Loop (for文)
' --------------------------------------------------
group sub-routine2
'  loop i=0, i<10, i++
  loop for each item
    a1 -> o1 : actiivity1
    a1 <-- o1
'    o1 --> a1
  end
end

' --------------------------------------------------
' Parallel (並列処理)
' --------------------------------------------------
group sub-routine3
  par
    a1 -> o1 : actiivity1
'    a1 <-- o1
    o1 --> a1
  else
    a1 -> o2: actiivity2
'    a1 <-- o2
    o2 --> a1
  end
end

' --------------------------------------------------

@enduml
