' --------------------------------------------------
' Function    : YAML_Format
' Author      : T. TANAKA
' Description : YAML_Formatの基本要素
' --------------------------------------------------

' --------------------------------------------------
' ◆参考文献：
' シンプルなテキストファイルで UML が書ける、オープンソースのツール.html
' https://plantuml.com/ja/
' --------------------------------------------------

@startyaml

'title YAML Format

' left to right direction

' --------------------------------------------------
' Category Definition
' --------------------------------------------------

' --------------------------------------------------
' Category Connection
' --------------------------------------------------
x: a
y:
 - b
 - c
 - d
z:
 z1: e
 z2: f
 z3: g
u:
 - h
 - 
  u1: i
  u2: j
  u3: k


@endyaml
